/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>


void
calculadora_1(char *host, double a, double b, int select)
{
	CLIENT *clnt;
	double  *result_1;
	dupla  suma_1_arg;
	double  *result_2;
	dupla  resta_1_arg;
	double  *result_3;
	dupla  multi_1_arg;
	double  *result_4;
	dupla  div_1_arg;

	suma_1_arg.a = a;
	suma_1_arg.b = b;
	resta_1_arg.a = a;
	resta_1_arg.b = b;
	multi_1_arg.a = a;
	multi_1_arg.b = b;
	div_1_arg.a = a;
	div_1_arg.b = b;


#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, CALCULADORA_VERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch(select)
	{
		case 1:
			result_1 = suma_1(&suma_1_arg, clnt);
			if (result_1 == (double *) NULL) {
			clnt_perror (clnt, "call failed");
			}
			printf("EL resultado de la suma fue:%lf", *result_1);	
		break;
			
		case 2:
			result_2 = resta_1(&resta_1_arg, clnt);
			if (result_2 == (double *) NULL) {
			clnt_perror (clnt, "call failed");
			}
			printf("EL resultado de la resta fue:%lf", *result_2);
		break;
			
		case 3:
			result_3 = multi_1(&multi_1_arg, clnt);
			if (result_3 == (double *) NULL) {
			clnt_perror (clnt, "call failed");
			}
			printf("EL resultado de la multiplicacion fue:%lf", *result_3);

		break;

		case 4:
			result_4 = div_1(&div_1_arg, clnt);
			if (result_4 == (double *) NULL) {
			clnt_perror (clnt, "call failed");
			}
			printf("EL resultado de la division fue:%lf", *result_4);
		break;
	}

	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int select;
	double a;
	double b;


	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	printf("Seleccione una operacion:\n1) Suma a + b\n2) Resta a - b\n3) Multiplicacion a*b\n4) Division a/b\n");
	do{
		scanf("%i", &select);
		fflush(stdin);
	}while(select < 1 && select > 4);
	
	printf("Seleccione el valor de a:\n");
	scanf("%lf", &a);
	fflush(stdin);
	printf("Seleccione el valor de b:\n");
	scanf("%lf", &b);
	fflush(stdin);

	calculadora_1(host, a, b, select);
	
exit (0);
}
