/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULADORA_H_RPCGEN
#define _CALCULADORA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct dupla {
	double a;
	double b;
};
typedef struct dupla dupla;

#define CALCULADORA 0x31111211
#define CALCULADORA_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  double * suma_1(dupla *, CLIENT *);
extern  double * suma_1_svc(dupla *, struct svc_req *);
#define RESTA 2
extern  double * resta_1(dupla *, CLIENT *);
extern  double * resta_1_svc(dupla *, struct svc_req *);
#define MULTI 3
extern  double * multi_1(dupla *, CLIENT *);
extern  double * multi_1_svc(dupla *, struct svc_req *);
#define DIV 4
extern  double * div_1(dupla *, CLIENT *);
extern  double * div_1_svc(dupla *, struct svc_req *);
extern int calculadora_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  double * suma_1();
extern  double * suma_1_svc();
#define RESTA 2
extern  double * resta_1();
extern  double * resta_1_svc();
#define MULTI 3
extern  double * multi_1();
extern  double * multi_1_svc();
#define DIV 4
extern  double * div_1();
extern  double * div_1_svc();
extern int calculadora_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dupla (XDR *, dupla*);

#else /* K&R C */
extern bool_t xdr_dupla ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULADORA_H_RPCGEN */
